name: "Artifacts"

on: [workflow_dispatch]

jobs:
  artifacts:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install --save-dev @babel/cli @babel/core @babel/plugin-proposal-class-properties @babel/plugin-proposal-optional-chaining @babel/plugin-syntax-dynamic-import @babel/plugin-transform-runtime @babel/preset-env @babel/preset-typescript @discordjs/ts-docgen @rollup/plugin-commonjs @rollup/plugin-node-resolve @types/eslint @types/estree @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser assert babel-cli browserify-zlib buffer eslint https-browserify process rollup rollup-plugin-peer-deps-external rollup-plugin-terser rollup-plugin-typescript2 stream-browserify stream-http typescript url util webpack webpack-cli

      - name: build
        run: npm run build

      - name: Get version & asign
        id: get_version
        run: |
          variable=$(jq --raw-output '.version' package.json)
          echo ::set-output name=version::$variable

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_version.outputs.version }}
          path: |
            dist/webpack
            dist/cjs
            dist/esm
            dist/types