name: "Artifacts"

on: [workflow_dispatch]

jobs:
  artifacts:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install --save-dev @babel/cli @babel/core @babel/preset-env @babel/preset-typescript babel-plugin-add-module-exports typescript @types/node

      - name: build
        run: npm run build

      - name: Get version & asign
        id: get_version
        run: |
          variable=$(jq --raw-output '.version' package.json)
          echo ::set-output name=version::$variable

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_version.outputs.version }}
          path: |
            dist/webpack
            dist/js