name: GH Release

on: [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/hyttpo-webpack.js"
        tag: "$(jq --raw-output '.version' package.json)"
        name: "$(jq --raw-output '.version' package.json)"
        token: ${{ secrets.GITHUB_TOKEN }}