name: "Release"

on: [workflow_dispatch]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm ci

      - name: build
        run: npm run build

      - name: Get version & asign
        id: get_version
        run: |
          variable=$(jq --raw-output '.version' package.json)
          echo ::set-output name=version::$variable

      - name: Publish webpack & releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/webpack/index.js"
          tag: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}